### ISSUE TITLE
parse nested lists properly

### ISSUE THREAD

**Issue by bantic** [bustle/mobiledoc-kit#189]
Content-Kit does not yet support nested lists, but we should probably accept pasted nested lists and just flatten them.

A nested list that has a `ul` as a descendant of an `li` (`ul` > `li` -> `ul`) will work but a nested list that is a descendant of the `ul` directly (i.e. `ul` -> `ul` -> `li`) is currently ignored when parsing. Any nested list should be parsed and flattened onto the topmost list.

**Comment by kevinansfield** [comment]
I believe this can be closed now. We still don't support nested lists in the mobiledoc format but parsing+flattening of nested lists is fully supported after recent changes to the the section parser.

`ul > li > ul > li` - will be flattened to a single top-level list
`ul > li > ul > li > p` - has same behaviour as when the `p` doesn't exist
`ul > li > ul > li > h1` - will not be flattened, "section"-creating elements such as `h1` will be retained but will break out of the list at the point they are encountered to maintain document heirarchy
