### ISSUE TITLE
Users should be able to edit links once they're created

### ISSUE THREAD

**Issue by cknific** [bustle/mobiledoc-kit#409]
Currently, if you select hyperlinked text and hit CMD+K (or use the link button on the mobiledoc demo site), the link will disappear. It would be useful to be able to edit the URL or name of the link when doing this.

**Comment by mixonic** [comment]
@cknific :-/ perhaps we should not have a hotkey for this at all. I believe you should be able to customize this behavior though, and I strongly encourage that over trying to change the upstream default implementation. I expect we could go back and forth on what the best UX for cmd-k is for a long time.

**Comment by cknific** [comment]
@mixonic I have a client that regularly uses CMD+K in the mobiledoc editor, so please do not remove the hotkey :) 

I can supply plenty of examples of applications that allow you to edit URLs with CMD+K. Take Google Docs, for example:

![test](https://cloud.githubusercontent.com/assets/903898/15488291/a83504f2-2109-11e6-81af-598a1767a53d.gif)

**Comment by mixonic** [comment]
@cknific totally. However mobiledoc-kit specifically attempts to *not* proscribe a user experience. It is best used as an SDK for building an editor experience. Where there are several ways of implementing an interaction, we are likely to choose the simplest and least surprising. For example, we would definitely not introduce a box with a lot of UI as in your Google Docs example.

Happy to leave this open and brainstorm ideas, but again, if you have a specific experience you want users to have you should likely build it on top of Mobiledoc-kit and not rely on our simple starting point.

**Comment by cknific** [comment]
@mixonic That's good to know. Thanks.

**Comment by ZeeJab** [comment]
Done here: https://github.com/bustle/mobiledoc-kit/pull/726
