### ISSUE TITLE
Document the marker/markerable concepts

### ISSUE THREAD

**Issue by courajs** [bustle/mobiledoc-kit#418]
They're mentioned off-hand a few times in the README, but it isn't clear what they mean. It seems like the best place to glean an understanding is [MOBILEDOC.md](https://github.com/bustlelabs/mobiledoc-kit/blob/master/MOBILEDOC.md), but "A marker means..." or "A markerable is..." explicitly somewhere would be nice.

**Comment by gpoitch** [comment]
Added in #585
