### ISSUE TITLE
Entering logograms issues in macOS

### ISSUE THREAD

**Issue by disordinary** [bustle/mobiledoc-kit#548]
This is the issue from the Ghost project.
https://github.com/TryGhost/Ghost/issues/8319

(The issue was submitted by @mach)

# Issue Summary

On Ghost Alpha's new text editor, Japanese text can't be typed correctly with Japanese IME (input method).

![image](https://cloud.githubusercontent.com/assets/82702/24944278/6743d564-1f95-11e7-80c8-eeedab8bbb7a.gif)

Steps to Reproduce

    Select Japanese IME (either Apple's JapaneseIM or Google's Japanese IME)
    Type "watasi"
    Press Enter key

Expected Result

At step 2: "watasi" should be converted to "わたし"
At step 3: "わたし" should be converted to "私"
Actual Result

At step 2: "watasi" is converted to "wあたし"
At step 3: "wあたし" is converted to "w"
Technical details:

    Ghost Version: 1.0.0-alpha.19
    Node Version: v6.10.2
    Browser/OS: Google Chrome / macOS Sierra
    Database: MySQL 5.7.17

**Comment by disordinary** [comment]
From testing it seems that it only occurs in an empty paragraph.

**Comment by taking** [comment]
Korean has the same problem.

**Comment by Adrift001** [comment]
Isn't this bug going to be fixed?

**Comment by kwmr** [comment]
When will they fix it?
I'm tired of waiting.

**Comment by taking** [comment]
> When will they fix it?
> I'm tired of waiting.

Haha not fix.

**Comment by sxueck** [comment]
It’s still half a year before 2020. But still not fixed, who knows what other editors?

**Comment by imyhui** [comment]
It’s been two years, still this error

**Comment by cmsax** [comment]
@soulteary addressed the problem, ref: [Issue 9801](https://github.com/TryGhost/Ghost/issues/9801).
However it's still not merged. The bug still there.

**Comment by kwmr** [comment]
uuuum...
The bug still there.

**Comment by cmsax** [comment]
Insert `markdown` block as a workaround.

**Comment by Smith-Cruise** [comment]
we are still enjoying this bug :)

**Comment by wbpmrck** [comment]
we are still enjoying this bug :)

**Comment by JianpingZong** [comment]
what's the essential thing of human being?
we are still enjoying this bug :)

**Comment by bin16** [comment]
The bug has been in ghost for two years, now 3.0 released...

**Comment by bin16** [comment]
@gpoitch Hi, want to know can this PR be merged? The bug has broken the editor of the ghost blog for more than one year https://github.com/TryGhost/Ghost/issues/9801

**Comment by gpoitch** [comment]
@bin16 this is just an issue not a PR.  Happy to merge a PR and release if someone fixes it.

**Comment by xiao99xiao** [comment]
I thought at least there was a partial fix https://github.com/bustle/mobiledoc-kit/pull/661

**Comment by bin16** [comment]
> @bin16 this is just an issue not a PR. Happy to merge a PR and release if someone fixes it.

Oh, sorry, please see #661

**Comment by xufangda** [comment]
> @bin16 this is just an issue not a PR. Happy to merge a PR and release if someone fixes it.

It has been fixed and PR one year ago, not been merged yet. 

Please have a look at  
**soulteary** comment  on Jan 27 in following post
https://github.com/TryGhost/Ghost/issues/9801

This issue caused very bad experience in all asian language user group.

**Comment by xufangda** [comment]
Please have a look at soulteary's bugfix. It works!

https://github.com/soulteary/mobiledoc-kit/commit/47ac0160f26de646f7e8f19c1a3026fb3636f8ca

**Comment by xufangda** [comment]
> @bin16 this is just an issue not a PR. Happy to merge a PR and release if someone fixes it.

Please have a look at soulteary's bugfix. It works!

https://github.com/soulteary/mobiledoc-kit/commit/47ac0160f26de646f7e8f19c1a3026fb3636f8ca

**Comment by wuliaopage** [comment]
Anyone who wants to push Ghost to fix this issue, please leave a message and show your support under this issue. https://github.com/TryGhost/Ghost/issues/11460

**Comment by iLoveBug** [comment]
Please review and try my pull request: https://github.com/TryGhost/mobiledoc-kit/pull/11, hope it could help.

**Comment by ksuk** [comment]
Is this the same and will it take time to correct?
I think everyone is doing their best!
![qtfg1-u5u90](https://user-images.githubusercontent.com/32995914/73737976-f16f1480-4786-11ea-84ec-9ca6b03b896f.gif)

**Comment by Smith-Cruise** [comment]
There will never fix it!

**Comment by ksuk** [comment]
If the line breaks and input do not work in Japanese, do you mean that there is no plan to correct it?

**Comment by Smith-Cruise** [comment]
This problem had existed for two years. 😞

**Comment by ksuk** [comment]
😭😭

**Comment by donamk** [comment]
I am shocked this issue did not fixed for two years

**Comment by bobby285271** [comment]
3 years now... :-(

**Comment by cmsax** [comment]
Work around: insert a markdown block then input & edit in this block.

**Comment by gclove** [comment]
When will this problem be resolved ... I am looking forward to it.

**Comment by quxiaolong1504** [comment]
3 years now... :-(

**Comment by secsilm** [comment]
Another solution: type a space first, then input what you want.

**Comment by kwmr** [comment]
^ That method doesn't work well in my environment. (macOS 10.5.5beta Safari)
It seems to work well on iOS.

**Comment by kwmr** [comment]
Finally, it has been three years.
I guess that means we should just give up on the solution.

**Comment by apfelbox** [comment]
Instead of just flooding this issue and annoying the contributors.. how about someone of the "+1" and "will this ever be fixed" crowd invest their time into providing a pull request with a fix instead? 😊

**Comment by ooohawk** [comment]
@kwmr yeah maybe they're like "f**k it, it's been three years and those who experienced this bug might already found an alternative way to solve this. I'll pretend this bug non-exist "

btw, try IA writer, it's great to have a local post file and u can publish the post in it.

**Comment by xiao99xiao** [comment]
Great we now have another great PR fix here. Let's see how long will they wait until that PR goes outdated. Or will someone merge it and slap in my face🤪
