### ISSUE TITLE
Builds fail on Travis CI

### ISSUE THREAD

**Issue by YoranBrondsema** [bustle/mobiledoc-kit#557]
This seems to an issue with `wd` which is a dependency of `saucie`. The version in yarn.lock (1.1.3) should be OK (see johanneswuerbach/saucie#65) so maybe a refresh of the cache on Travis would solve the issue? I don't think I can do that.

**Comment by bantic** [comment]
Seems to be ok again now after triggering a rebuild with clean cache. Thanks for reporting!
