### ISSUE TITLE
disableEditing allows for copy, paste, and cut

### ISSUE THREAD

**Issue by TSiege** [bustle/mobiledoc-kit#572]
At Bustle we have writers accidentally pasting values into mobiledoc bodies that are created with `disableEditing` called.  The writers are then unable to delete the text; however, it can be removed with cut

Code:
We are using Ember Mobiledoc Editor `v0.5.12`, with settings `isEditingDisabled=true` in the template, which triggers [`disableEditing`](https://github.com/bustle/ember-mobiledoc-editor/blob/66d0e655ec95bc1a0f08ac2f1842802b2e913f63/addon/components/mobiledoc-editor/component.js#L258-L260)

Steps to reproduce:
- Create new mobiledoc editor with `disableEditing`
- Click on the body (no cursor should appear)
- Paste text
- Highlighting text and deleting does nothing
- Highlighting text and cut to remove text

**Comment by bantic** [comment]
+1 thanks for reporting. Suspending the editor's `EventManager` altogether when editing is disabled seems like a good idea. I'll issue a PR
