### ISSUE TITLE
Unbalanced Tag errors / avoiding simple-dom

### ISSUE THREAD

**Issue by kevinansfield** [bustle/mobiledoc-kit#576]
I'd be interested in having a chat about escaping from `mobiledoc-dom-renderer`/`simple-dom` for certain cards in order to output raw HTML (if something like that is even possible!) or alternative methods to avoid `simple-dom` errors.

Background:
In Ghost 1.x we're currently storing a very basic mobiledoc document for each post which contains a single markdown card - we're not using the mobiledoc-kit editor at the moment but we wanted to store mobiledoc ready to bring our full editor online later.

During the alpha/beta phase we were using the `mobiledoc-dom-renderer` on the server via node.js to render the single-card mobiledoc document. We immediately ran into issues with `Unbalanced tag` errors because markdown allows freeform HTML input and it's quite likely we'll save drafts where the HTML is in an incomplete state. To work around this we were running the markdown renderer's output through `jsdom` before passing it through `simple-dom` which for the most part worked fine.

However, as soon as we started trying to upgrade real user sites from 0.x to 1.x (where the markdown content for each post is pulled into a mobiledoc markdown card and then rendered to HTML) almost every import we tried was failing with `Unbalanced tag` errors. It seemed that`simple-dom` is very fragile when dealing with HTML input, to the point where even `jsdom` sanitized output can cause problems so we had to completely remove `mobiledoc-kit` from the rendering process. We're now manually extracting the markdown content and running that through a markdown renderer to generate the HTML for each post - great for avoiding errors, not so great for the future of our editor.

Ideally we'd like to be able to bypass `simple-dom` entirely for cards which allow freeform HTML input so we can complete avoid this issue for both old and new content, but if that's not possible what would be the suggested approach to using mobiledoc in this situation?

**Comment by mixonic** [comment]
The simplest thing I see is to try and continue using SimpleDOM via the `createRawHTMLSection` method on `document`. In [simple-dom/lib/simple-dom/document.js](https://github.com/ember-fastboot/simple-dom/blob/83768375f732ee35564b60c5b1e2431d6b64519e/lib/simple-dom/document.js#L34).

The serialization for this kind of node is simply its content: In [simple-dom/lib/simple-dom/html-serializer](https://github.com/ember-fastboot/simple-dom/blob/f9f2353022b1b047e97fc4139bb3c9d2f9ba1347/lib/simple-dom/html-serializer.js#L74).

Beyond that, two other ideas:

* Can you just use a real DOM? You mentioned `jsdom` so I presume no, we're talking about Node.
* If `RawHTMLSection` isn’t sufficient, we once had an [HTML renderer](https://github.com/bustle/mobiledoc-html-renderer) and we could bring it back. I hope we can find another solution beside maintaining a second renderer though.

**Comment by kevinansfield** [comment]
Thanks! `createRawHTMLSection` looks to be just what was needed 😄 Can't believe I missed that when looking through the SimpleDOM api.

I've implemented it here https://github.com/TryGhost/Ghost/pull/8937, initial tests look promising. We'll run it through some more rigorous tests on Monday but it sounds like it will be 👌

**Comment by kevinansfield** [comment]
Closing as `document.createRawHTMLSection` fits our needs perfectly. Thanks for pointing me in the right direction 😄
