### ISSUE TITLE
Cursor is placed at the start of the line when typing special characters 

### ISSUE THREAD

**Issue by kiwicopple** [bustle/mobiledoc-kit#581]
Note: using version 0.10.19

If the first letter in a new paragraph is a character like "#" or "-", after the user has typed the symbol the cursor is placed at the start.

### Steps to replicate 

1. In an editor, type the symbol "#"
2. Next, type a letter "a"

The expected output in the editor should be "#a", however it is actually "a#"

**Comment by YoranBrondsema** [comment]
@kiwicopple Thanks for reporting. I can reproduce the bug and it seems to be caused by my own changes in #575. Looking into it now!

**Comment by YoranBrondsema** [comment]
#582 reverts the changes and I added some more info there!

**Comment by kiwicopple** [comment]
Thanks for the speedy fix @YoranBrondsema !
