### ISSUE TITLE
Selection is off when triple-clicking on Firefox

### ISSUE THREAD

**Issue by YoranBrondsema** [bustle/mobiledoc-kit#592]
I found this out when trying to cut triple-clicked selected text:

![mobiledoc](https://user-images.githubusercontent.com/1374412/33335041-7c8c6a7a-d431-11e7-8da3-bab3d5fc6f32.gif)

The cause of this is explained here: https://stackoverflow.com/a/21234837/1269194.

**Comment by kevinansfield** [comment]
This also manifests itself when typing to replace a triple-click selection:

![firefox-triple-click-type](https://user-images.githubusercontent.com/415/42697980-8be70918-86b4-11e8-8e3a-c0987070c18e.gif)
