### ISSUE TITLE
Copy-pasting from Word or LibreOffice Writer removes spaces between words

### ISSUE THREAD

**Issue by YoranBrondsema** [bustle/mobiledoc-kit#600]
See [this comment](https://github.com/textAngular/textAngular/issues/598#issuecomment-92419636) for an explanation.

I think this issue comes from a single-character typo though :-). The solution in https://github.com/bustle/mobiledoc-kit/issues/333 mentions that newlines should be replaced with space characters. However, the actual implementation for the fix in https://github.com/bustle/mobiledoc-kit/commit/28ec7817a82720fc47d2a3aa704a0a143970955b replaces them with an empty string instead.

**Comment by bantic** [comment]
fixed by #601

**Comment by bantic** [comment]
released in v0.10.21 https://github.com/bustle/mobiledoc-kit/releases/tag/v0.10.21 thank you!
