### ISSUE TITLE
Cards don't work on the demo website

### ISSUE THREAD

**Issue by kuba-orlik** [bustle/mobiledoc-kit#702]
I've just tried running the [demo](http://bustle.github.io/mobiledoc-kit/demo/) and when I try to use the "Insert kitten card" button, nothing happens and the js console shows an error:

```
Uncaught TypeError: Cannot read property 'split' of undefined
```

**Comment by gpoitch** [comment]
Fixed in https://github.com/bustle/mobiledoc-kit/pull/699
