### ISSUE TITLE
Question: extensions?

### ISSUE THREAD

**Issue by shaunc** [bustle/mobiledoc-kit#720]
Is there a guide to extending mobiledoc for extra wysiwyg widgets? In particular I'm interested in whether it would be possible/how hard it would be to add mathjax support to a mobiledoc editor?

**Comment by pankajpatel** [comment]
I think it is possible. You can take a look at the [Ghost Admin Panel (Koenig Editor)](https://github.com/TryGhost/Ghost-Admin/tree/master/lib/koenig-editor) to get some idea on how to extend Mobiledoc.

**Comment by gpoitch** [comment]
Extensions are called "cards". Docs here: https://github.com/bustle/mobiledoc-kit/blob/master/CARDS.md
