### ISSUE TITLE
Edit mode by default in plain javascript?

### ISSUE THREAD

**Issue by jacobsokora** [bustle/mobiledoc-kit#727]
I'm building an editor that only needs to be able to edit cards, not display them. I'm struggling to find a way to do this in plain javascript, can anyone help?

**Comment by jacobsokora** [comment]
I no longer need this feature for my editor, but it would still be nice to have documentation so I’m leaving this open!

**Comment by gpoitch** [comment]
Since you create the DOM for cards you would just always create the editing DOM.
There is a flag you typically check to known whether to render the editing or display mode which you can just ignore

https://github.com/bustle/mobiledoc-kit/blob/master/CARDS.md
