### ISSUE TITLE
Why mobile-doc-vue repo is archived?

### ISSUE THREAD

**Issue by gustawdaniel** [bustle/mobiledoc-kit#735]
README of this repo indicates link:

https://github.com/alidlo/vue-mobiledoc-editor

but it is archived. Is anyone knows why? Where can I read about history and perspectives of mobiledoc format in context of vue?

**Comment by ZeeJab** [comment]
Hi @gustawdaniel, we don't maintain that library so unfortunately I'm unaware of the reason for why it's been archived. Maybe reach out to them directly on that repo?
