### ISSUE TITLE
v0.12.4 based update for IME bugs

### ISSUE THREAD

**Issue by tnmt** [bustle/mobiledoc-kit#746]
Hi.

I made PR #745 but there is no appropriate branch to contribute.

Could you cherry-pick 8f05bcf534dd33ee5ecf294bc8d9e4935f9141a8 to 0.12.4 and release in 0.12.5 ?

Thanks.

**Comment by ZeeJab** [comment]
I prefer not to, but if it's a blocker we can consider it. What is your blocker to upgrading to 0.13.x?

**Comment by tnmt** [comment]
I use Ghost CMS https://github.com/TryGhost/Ghost and Ghost uses own [TryGhost/mobiledoc-kit](https://github.com/TryGhost/mobiledoc-kit) based on bustle/mobiledoc-kit.
Unfortunately TryGhost/mobiledoc-kit is still based on 0.12.x. I guess there are some problem to catch up original 0.13.x changes.

I once planed to patch TryGhost/mobiledoc-kit, but I guess that TryGhost/mobiledoc-kit is not only project which use 0.12.x bustle/mobiledoc-kit, so I suggest this Issue.

Should I limit to patch each project which use old mobiledoc-kit ?

**Comment by ZeeJab** [comment]
Released v0.12.5 with the IME fix backported. Let me know if you run into any trouble.

**Comment by tnmt** [comment]
Thank you for release v0.12.5 !!
