### ISSUE TITLE
0.13.2 release on npm for IME bugs

### ISSUE THREAD

**Issue by YoranBrondsema** [bustle/mobiledoc-kit#750]
Related to https://github.com/bustle/mobiledoc-kit/issues/746. I see that v0.13.2-pre.0 has been tagged but not yet released on NPM. Is there a way we can release 0.13.2 on NPM so that the IME bug fix is published?

**Comment by ZeeJab** [comment]
@YoranBrondsema yisss def! I'll do a release by end of week 🙏

**Comment by YoranBrondsema** [comment]
Great, thank you!

**Comment by ZeeJab** [comment]
done!

**Comment by YoranBrondsema** [comment]
Perfect, thank you!
