### ISSUE TITLE
Potential security problem(s)

### ISSUE THREAD

**Issue by intrigus-lgtm** [bustle/mobiledoc-kit#757]
Hi, could you please create a new [draft security advisory](https://help.github.com/en/github/managing-security-vulnerabilities/creating-a-security-advisory) and 
[invite me](https://help.github.com/en/github/managing-security-vulnerabilities/adding-a-collaborator-to-a-security-advisory) to it?
Any other private communication channel would also be fine.
I think I've found a potential security problem.

**My disclosures always follow Github's 90-day [disclosure policy](https://securitylab.github.com/advisories#policy) (I'm not an employee of Github, I just like their policy).**

**Comment by gpoitch** [comment]
https://github.com/bustle/mobiledoc-kit/blob/master/SECURITY.md

**Comment by intrigus-lgtm** [comment]
I have just sent you a mail with details.
