### ISSUE TITLE
Can't using Korean in ios mobile

### ISSUE THREAD

**Issue by spectroom-project** [bustle/mobiledoc-kit#763]
![4f74f22053d80bac04b042f443ebef7b0ece1682](https://user-images.githubusercontent.com/74969914/178478001-8da784c4-fdd5-4131-a527-3458e9357e77.jpg)

Ghost CMS using mobiledoc-kit.
There is a Korean typing error in ios mobile.
(It works fine with window PC and Mac OS)

The separation of consonants and vowels.
It has to be **'안녕하세요'.** Not **'ㅇㅏㄴㄴㅕㅇㅎㅏㅅㅔㅇㅛ'**

I want to use Korean on my mobile.

**Comment by spectroom-project** [comment]
Is anybody out there? ㅠ0ㅠ

**Comment by gpoitch** [comment]
I believe this may have been fixed by #764.

Testing this out with the Korean keyboard renders exactly what I type and copy/pasting you example text also renders exactly what was copied.
